export function useFetchProducts(): Product[] {
  const products = [
    {
      id: 11,
      name: 'Peekabo',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/Peekabo/thumbnail.png',
      active: true,
      desc: 'This whitening body cream contains unique combination of Deep White Essence, helps lighten your skin and moisturizes dry skin for noticeably white and smoother',
      price: '3300.00',
      discount_price: '0.00',
      final_price: '3300.00',
      qty: 7,
    },
    {
      id: 10,
      name: 'Nivea - Extra white',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/Nivea - Extra white/thumbnail.png',
      active: true,
      desc: 'This whitening body cream contains unique combination of Deep White Essence, helps lighten your skin and moisturizes dry skin for noticeably white and smoother',
      price: '4700.00',
      discount_price: '0.00',
      final_price: '4700.00',
      qty: 16,
    },
    {
      id: 9,
      name: 'Olay',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/Olay/thumbnail.png',
      active: true,
      desc: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur',
      price: '3200.00',
      discount_price: '0.00',
      final_price: '3200.00',
      qty: 22,
    },
    {
      id: 8,
      name: 'Cera Ve',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/Cera Ve/thumbnail.jpg',
      active: true,
      desc: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur',
      price: '2000.00',
      discount_price: '0.00',
      final_price: '2000.00',
      qty: 19,
    },
    {
      id: 7,
      name: 'St Ives',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/St Ives/thumbnail.png',
      active: true,
      desc: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      price: '1500.00',
      discount_price: '0.00',
      final_price: '1500.00',
      qty: 9,
    },
    {
      id: 6,
      name: 'Blue Moon',
      url: 'https://storage.googleapis.com/safemonk/business/2/product/Blue Moon/thumbnail.png',
      active: true,
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      price: '1800.00',
      discount_price: '0.00',
      final_price: '1800.00',
      qty: 13,
    },
  ];

  return products;
}
